# NUMPY

In [1]:
import numpy as np

np.sqrt(25)


5.0

# Arrays


## np.array()

In [3]:
a = [ 0,1 ,2 ,3 ,4, 5]

type(a)

list

In [49]:
type(np.array(a))
print(np.array([0, 1, 2, 3]))

[0 1 2 3]


## np.arange()

In [7]:
b = np.arange(4, 25, 2)

print(b)

[ 4  6  8 10 12 14 16 18 20 22 24]


## np.linspace()

In [10]:
c = np.linspace(1, 40, 5)

c

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])

## np.zeros()

In [13]:
d = np.zeros(50)

d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## np.ones()

In [15]:
e = np.ones(50)

e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [17]:
array_2d = np.array([d,e])
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


## array.shape

In [19]:
array_2d.shape

(2, 50)

## array.size

In [20]:
array_2d.size


100

## array.ndim


In [21]:
array_2d.ndim


2

## Operaciones con arrays

In [22]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

In [23]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)


In [24]:
array_1 * array_2

array([ 4, 10, 18])

## Funciones

## np.reshape()

In [25]:
array_2d.shape

(2, 50)

In [26]:
f = np.reshape(array_2d, (5, 20))

In [27]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [28]:
f.shape

(5, 20)

## array.T --> Transpose

In [32]:
a = np.array([[1, 2, 3, 4, 5], [10, 20, 30 ,40 ,50]])

In [33]:
a.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

## np.random

### np.random.randint

In [36]:
np.random.randint(0, 300)

75

## np.where

**Los elementos que cumplan la condición multiplicalos por 10 y los que no la cumplan restale 5**

In [37]:
np.where(array_2d == 1, array_2d * 10, array_2d - 5)


array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# Estadistica

## Distribución 

In [39]:
array_normal = np.random.normal(50, 5, 1000)

In [40]:
array_normal


array([49.80978799, 42.6333174 , 54.65789071, 49.03672935, 44.12710298,
       49.89675366, 52.36678088, 49.26122809, 50.93358038, 48.0234124 ,
       54.06244505, 54.83063699, 54.57813073, 49.54824795, 46.17108362,
       46.09707079, 53.90287249, 55.5403564 , 50.259781  , 55.60137966,
       45.7591262 , 53.96397052, 41.93932565, 47.66859269, 52.30207588,
       58.34936429, 46.80194915, 52.31439032, 54.01359096, 54.13422307,
       46.9212452 , 52.8048822 , 47.73811121, 58.96886045, 47.55734239,
       51.01717306, 51.06547589, 56.41712416, 55.28645639, 47.89230727,
       51.03220531, 49.54065714, 44.9091239 , 54.66032086, 51.21286791,
       47.05592247, 57.94467148, 54.38696058, 49.09157942, 50.84919044,
       51.55305726, 61.84402355, 44.95661251, 54.92544428, 49.48053582,
       56.85137332, 48.25062673, 51.58130638, 48.58684027, 43.06200301,
       54.81507671, 52.42693295, 48.63853293, 44.38526676, 52.89564904,
       57.47968052, 43.88151335, 50.6138826 , 44.04131781, 49.93

## np.mean

In [41]:
np.mean(array_normal)

50.04859468531908

## np.median

In [42]:
np.median(array_normal)

50.00625444923344

## np.std

In [44]:
np.std(array_normal)

5.070225930758908