# NUMPY

In [1]:
import numpy as np

np.sqrt(25)


5.0

# Arrays


## np.array()

In [3]:
a = [ 0,1 ,2 ,3 ,4, 5]

type(a)

list

In [5]:
type(np.ndarray(a))

numpy.ndarray

## np.arange()

In [7]:
b = np.arange(4, 25, 2)

print(b)

[ 4  6  8 10 12 14 16 18 20 22 24]


## np.linspace()

In [10]:
c = np.linspace(1, 40, 5)

c

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])

## np.zeros()

In [13]:
d = np.zeros(50)

d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## np.ones()

In [15]:
e = np.ones(50)

e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [17]:
array_2d = np.array([d,e])
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


## array.shape

In [19]:
array_2d.shape

(2, 50)

## array.size

In [20]:
array_2d.size


100

## array.ndim


In [21]:
array_2d.ndim


2

## Operaciones con arrays

In [22]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

In [23]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)


In [24]:
array_1 * array_2

array([ 4, 10, 18])

## Funciones

## np.reshape()

In [25]:
array_2d.shape

(2, 50)

In [26]:
f = np.reshape(array_2d, (5, 20))

In [27]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [28]:
f.shape

(5, 20)

## array.T --> Transpose

In [32]:
a = np.array([[1, 2, 3, 4, 5], [10, 20, 30 ,40 ,50]])

In [33]:
a.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])